### ISSUE TITLE
big-endian to little-endian conversion 

### ISSUE THREAD

**Issue by crypt0inf0** [MattyAB/BitcoinMiner#2]
Hi, I can see you provided the little-endian values on [`main.cpp#L12`](https://github.com/MattyAB/BitcoinMiner/blob/main/main.cpp#L12) 

Can you provide a function to convert big-endian to little-endian so that we can use the blockchain data as it is?

**Comment by crypt0inf0** [comment]
I did it myself checkout https://github.com/crypt0inf0/BitcoinMiner

**Comment by MattBeton** [comment]
That's great - is there any chance you can create a pull request and I'll merge these changes into the main branch?
